# Site settings
title: Chic & Flow
email: sogoald@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I want to make online shopping easier for you, by bringing my favorite pieces from clothing websites into one place. On almost every item, you’ll see why I chose it and often some TIP’s on how to style it
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.chicandflow.com" # the base hostname & protocol for your site
twitter_username: SogoalDavani
github_username:  SogoalDavani
paginate: 15

# Build settings
markdown: kramdown
